name: CI
run-name: CI

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  checks:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.event.head_commit.author.email != 'semantic-release'
    uses: muxu-io/shared-workflows/.github/workflows/python-checks.yml@master
    secrets: inherit
